sih_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from api.views import *
from login.views import *

from django.contrib.auth import views
from login.forms import LoginForm
from teacheradd.views import *
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', views.logout, {'template_name': 'home.html'}),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),
    url(r'^home/$', views.logout, {'template_name': 'home.html'}),

    url(r'^$', home, name='home'),
    url(r'^mapcountry/$', map_country_function),
    url(r'^mapstate/$', map_state_function),
    url(r'^mapdistrict/$', map_district_function),
    url(r'^mapcity/$', map_city_function),
    url(r'^schoolteachers/$', teacher_list),

    url(r'^testmap/$', test_map),
    url(r'^dummy/$', dummy),

    url(r'^school/$', AddSchool),
    # urls for api
    url(r'^api/create/', createUser),
    url(r'^api/update/', updateUserDetails),
    url(r'^api/signup/', signupUser),
    url(r'^api/login/', loginUser),
    url(r'^api/verify/', verifyUser),
    url(r'^api/logout/', logoutUser),
    url(r'^api/markattendance/', markAttendance),
    url(r'^api/isschooladded/', isSchoolAdded),
    url(r'^api/addschool/', addSchoolToUser),
    url(r'^api/latlong/', getLatLong),
    url(r'^api/presentholidays/', getPresentAndHolidays),

    url(r'^fill_details/$',fill_details,name='fill_details'),
    url(r'^check_user/$',check_user,name='check_user'),
    url(r'^valid_user/$',TemplateView.as_view(template_name='user_valid.html'),name='user_valid'),
]

api/forms.py
from django import forms
from api.choices import * 
# Create your forms here.

class resumeForm(forms.Form):
	username = forms.CharField(max_length=200)
	name = forms.CharField(max_length=50)
	age = forms.IntegerField()
	contactNum = forms.CharField(max_length=12)
	email = forms.CharField(max_length=100)
	areaOfExpertise = forms.CharField(max_length=100)
	address = forms.CharField(max_length=200)
	city = forms.CharField(max_length=50)
	state = forms.ChoiceField(choices = STATE_CHOICES, label="State", initial='', widget=forms.Select(), required=True)
	prefferedLocation = forms.CharField(max_length=50)
	qualification = forms.CharField(max_length=100)
	teachingExperience = forms.IntegerField()
	currentSchool = forms.CharField(max_length=100)
	
	

login/forms.py
#login/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from login.models import *

# If you don't do this you cannot use Bootstrap CSS
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password'}))

class schoolAdd(forms.Form):
	#user = forms.CharField(max_length=50)
	pass1=forms.CharField(label="Password" ,max_length=100)
	#user = forms.CharField(label="Username", max_length=30,widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    #pass1 = forms.CharField(label="Password", max_length=30,widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password'}))

	name=forms.CharField(label="Name",max_length=100)
	state=forms.ModelMultipleChoiceField(label="State",queryset=State.objects.all())
	timing=forms.CharField(label="Timing",max_length=100)
	address=forms.CharField(label="Address",max_length=100)
	district=forms.ModelMultipleChoiceField(label="District",queryset=District.objects.all())
	city=forms.ModelMultipleChoiceField(label="City",queryset=City.objects.all())
	numOfStudents=forms.IntegerField(label="Num of Students")
	numOfTeachers=forms.IntegerField(label="Num of Teachers")
	latitude=forms.FloatField(label="Latitude")
	longitude=forms.FloatField(label="longitude")
	wifi_zone=forms.BooleanField(label="Wifi Zone")

templates/about.html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>Searchable Map Template Demo</title>
    <meta charset='utf-8' />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content='' name='description' />
    <meta content='' name='author' />
    <!-- Styles -->
    <link rel="stylesheet" href="css/bootstrap.min.css"/>
    <link rel="stylesheet" href="css/custom.css"/>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script type="text/javascript" src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class='navbar navbar-default navbar-static-top'>
      <div class='container-fluid'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class='navbar-brand' href='index.html'>Searchable Map Template</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="index.html">Map</a></li>
            <li class='active'><a href="about.html">About</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class='container-fluid'>
      <div class='row'>
        <div class='col-md-12'>
          <h1>About</h1>
          <p>This is a demo of <a href='http://derekeder.com'>Derek Eder's</a> <a href='http://derekeder.com/searchable_map_template/'>Searchable Map Template</a> using Google <a href='http://support.google.com/fusiontables/answer/2571232?hl=en&ref_topic=1652595'>Fusion Tables</a>.</p>
          <p>Use this page to give even more context to your map.</p>
        </div>
      </div>
    </div>

    <script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
  </body>
</html>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Auth Demo</title>
                <!-- Core CSS - Include with every page -->
                <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
                <link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
                <script src = "{% static 'js/jquery-1.12.4.min.js' %}"></script>
                <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">

                </head>
                <body>
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-barand" href="#">SHIKSHAK AROHAN</a>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/home">home</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="/logout">Logout</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>

                {% block content %}
                {% endblock %}


                    <!-- Core Scripts - Include with every page -->



        {% block javascript %}
                    <script src = "{% static 'js/bootstrap.min.js' %}"></script>
                    <script src="{% static 'js/select2.min.js' %}"></script>
        {% endblock %}

        {% block additional_scripts %}

        {% endblock %}


            </body>
 </html>

templates/check_user.html
{% extends 'base.html' %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="post">
    {% csrf_token %}
    <input type="text" class="form-control" placeholder="Username" name="u" 
    style="width:30%;">
<button type="submit" class="btn btn-info">Check</button>
</form>

{% endblock %}

templates/error400.html
error 400

templates/fill_details.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" class="post-form">{% csrf_token %}
	{{form.as_p}}
<button type="Submit" class="save btn btn-default">
	Save
</button>
</form>

{% endblock %}

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang='en'>
<head>
    <title>Shikshak Arohan</title>
    <meta charset='utf-8' />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content='' name='description' />
    <meta content='' name='author' />
    <!-- Styles -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/map.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}"/>

    <link rel="stylesheet" href="{% static 'css/jquery-ui.structure.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/jquery-ui.theme.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}"/>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/fusioncharts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/themes/fusioncharts.theme.fint.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/fusioncharts.charts.js' %}"></script>


    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">


</head>
<body>
<div class='navbar navbar-default navbar-static-top'>
    <div class='container-fluid'>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class='navbar-brand' href='#'>Shikshak Arohan</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class='active'><a href="../mapcountry">Map</a></li>
                <li><a href="">About</a></li>
            </ul>
        </div>
    </div>
</div>
<div class='container-fluid'>
    <div class='row'>
        <div class='col-md-4'>
            <div id="data_form_container">
                <h4>
                    Filters
                </h4>
                <div id="from_to_datepicker" class="date-picker">
                    <div class="input">
                        <label for="from_date">From Date</label>
                        <input id="from_date" class="calendar calendar-to" value="{{from}}" readonly>
                    </div>

                    <div class="input">
                        <label for="to_date">To Date</label>

                        <input id="to_date" class="calendar calendar-from" value="{{to}}" readonly>
                    </div>

                </div>

                <!-- 	<input id="datepicker"> -->
                <h4>
                    Category Filter:
                </h4>
                <div class="page">
                    <div class="select-dropdown">
                        <select id="teachercategory">
                            <option value="all" {% if teacher_category == '' or teacher_category == 'all' %} selected {%endif%}>All</option>
                            <option value="primary" {% if teacher_category == 'primary' %} selected {%endif%} >Primary</option>
                            <option value="secondary"  {% if teacher_category == 'secondary' %} selected {%endif%} >Secondary</option>
                            <option value="senior"  {% if teacher_category == 'senior' %} selected {%endif%} >Senior</option>
                        </select>
                    </div>
                </div>
                <br/> <br/>
                <a id="apply_button" class="btn" href="{{ url }}" id="apply-button">Apply</a>



            </div>
            <div id="map_legend_left">
                <img src="{% static 'images/ncpcr.jpg' %}" style="width:100%; height:auto">

            </div>
        </div>

        <div class='col-md-8'>
            <div id="map_legend_top">
                <div class="stats_box" id="box_1">
                    <p class="stat_number">{{ count_st_ratio }}</p>
                    <p class="stat_desc">Avg Student-Teacher Ratio</p>
                </div>
                <div class="stats_box" id="box_2">
                    <p class="stat_number">{{ count_students }}</p>
                    <p class="stat_desc">Total Number of Students</p>
                </div>
                <div class="stats_box" id="box_3">
                    <p class="stat_number">{{ count_teachers }}</p>
                    <p class="stat_desc">Total Number of Teachers </p>
                </div>
                <div class="stats_box" id="box_4">
                    <p class="stat_number">{{ count_schools }}</p>
                    <p class="stat_desc">Total Number of Schools</p>
                </div>
            </div>
            <div class="outer" style="overflow:hidden; width:100%; height:100%; padding:-5px; ">
                <div id="chart-container" style="transition: all 0.3s 0s ease-in-out;">FusionCharts will render here</div>
            </div>
        </div>
    </div>

</div>
<a href="javascript:void(0)" onclick="enlargex()" id="zoomtab">+ Enlarge</a>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></scri<pt>
    <script type="text/javascript">
        //     var prevFn = function(today){
        //     if(calBody){
        //         calBody.innerHTML = "";
        //     }
        //     if(mm===1){
        //         mm = 12;
        //         yyyy=yyyy-1;
        //     }
        //     else {
        //         mm = Number(mm)-1;
        //         yyyy=yyyy;
        //     }
        //     createBody(today);
        // };
        // var nextFn = function(today){
        //     if(calBody){
        //         calBody.innerHTML = "";
        //         }
        //     if(mm===12){
        //         mm=1;
        //         yyyy = yyyy+1;
        //     }
        //     else{
        //         mm = Number(mm)+ 1;
        //         yyyy = yyyy;
        //     }
        //     console.log(dd + " "  + mm + " " + yyyy );
        //     createBody(today,dd,mm,yyyy);
        // }
        // // prevB = document.getElementById(prevFn);
        // // nextB = document.getElementById(nextFn);
    </script>
    <script type="text/javascript">
        function enlargex(){
            var trVal = $('#chart-container').css('transform');
            if (trVal != 'none' && trVal.split('(')[1].split(')')[0].split(',')[0] == '1.4') {
                $('#chart-container').css('transform','scale(0)');
                $('#chart-container').css('-webkit-transform','scale(1)');
                $('#chart-container').css('-webkit-transform-origin','0 0');
                $('#chart-container').css('-moz-transform','scale(1)');
                $('#chart-container').css('-moz-transform-origin','0 0');
                $('#chart-container').css('-o-transform','scale(1)');
                $('#chart-container').css('-o-transform-origin','0 0');
                $('#chart-container').css('-ms-transform','scale(1)');
                $('#chart-container').css('-ms-transform-origin','0 0');
                $('#chart-container').css('margin-left','0px');
                $('#zoomtab').html('+ Enlarge');
            } else {
                $('#chart-container').css('transform','scale(1.4)');
                $('#chart-container').css('margin-left','-125px');
                $('#chart-container').css('-webkit-transform','scale(1.4)');
                $('#chart-container').css('-webkit-transform-origin','0 0');
                $('#chart-container').css('-moz-transform','scale(1.4)');
                $('#chart-container').css('-moz-transform-origin','0 0');
                $('#chart-container').css('-o-transform','scale(1.4)');
                $('#chart-container').css('-o-transform-origin','0 0');
                $('#chart-container').css('-ms-transform','scale(1.4)');
                $('#chart-container').css('-ms-transform-origin','0 0');
                $('#chart-container').css('-ms-transform-origin','0 0');
                $('#zoomtab').html('- Shrink');
            }
        }
</script>




</script>

<script>
var $to = '{{ to }}';
var $from = '{{ from }}';
var $teacher_cat = '{{ teacher_category }}';
$(function() {
    $( ".calendar" ).datepicker({
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        beforeShow: function(input, inst) {
            inst.dpDiv.css({"z-index":99999999999999});
        }
    });
    $(document).on('click', '.date-picker .input', function(e){
        var $me = $(this),
            $parent = $me.parents('.date-picker');
        $parent.toggleClass('open');
    });
    $(".calendar-to").on("change",function(){
        var $me = $(this),
            $selected = $me.val(),
            $parent = $me.parents('.date-picker');
        $parent.find('.result').children('span').html($selected);
        $to = $selected;
        $("#apply-button").attr("href", "{{ url }}" + "&to=" + $to + "&from=" + $from + "&teachercategory=" + $teacher_cat);
    });
    $(".calendar-from").on("change",function(){
        var $me = $(this), $selected = $me.val(), $parent = $me.parents('.date-picker');
        $parent.find('.result').children('span').html($selected);
        $from = $selected;
        $("#apply-button").attr("href", "{{ url }}" + "&to=" + $to + "&from=" + $from + "&teachercategory=" + $teacher_cat);
    });
});
$('#teachercategory').on('change', function(){
    $teacher_cat = this.value;
    $("#apply-button").attr("href", "{{ url }}" + "&to=" + $to + "&from=" + $from + "&teachercategory=" + $teacher_cat);
});
</script>
<script type="text/javascript">
    var json_data = JSON.parse('{{ json_map | escapejs }}');
    FusionCharts.ready(function () {
        var wrCoverage = new FusionCharts(json_data);
        //Configure the second level chart's properties
        wrCoverage.configureLink({
            type: "mscombidy2d",
            overlayButton: {
                message: 'Back',
                fontColor: '880000',
                bgColor: 'FFEEEE',
                borderColor: '660000'
            }
        }, 0);
        wrCoverage.render();
    });
</script>
<script type="text/javascript" src="{% static 'js/jquery.address.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/rough.html
{% load staticfiles %}

<!DOCTYPE html>
<html ng-app="ShikshakArohan" ng-cloak>
<head>
    <title></title>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'css/map.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/fusioncharts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/themes/fusioncharts.theme.fint.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/fusioncharts.charts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/fusioncharts.charts.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{% static 'js/map/map.js' %}"></script>
</head>
<body>

<div class="date-picker">
	<div class="input">
		<div class="to result">To: <span></span></div>
		<button><i class="fa fa-calendar"></i></button>
	</div>
	<div class="calendar calendar-to"></div>
</div>

<div class="date-picker">
	<div class="input">
		<div class="from result">From: <span></span></div>
		<button><i class="fa fa-calendar"></i></button>
	</div>
	<div class="calendar calendar-from"></div>
</div>
<a class="btn" href="{{ url }}" id="apply-button">Apply</a>

<div id="chart-container" style="margin-top: 80px;">FusionCharts will render here</div>

<script type="text/javascript">
    var json_data = JSON.parse('{{ json_map | escapejs }}');
    FusionCharts.ready(function () {
    var wrCoverage = new FusionCharts(json_data);
    //Configure the second level chart's properties
    wrCoverage.configureLink({
        type: "mscombidy2d",
        overlayButton: {
            message: 'Back',
            fontColor: '880000',
            bgColor: 'FFEEEE',
            borderColor: '660000'
        }
    }, 0);
    wrCoverage.render();
});


</script>
</body>
</html>

templates/school.htm
{% extends 'base.html' %}

{% block content %}
<style>
    .school_form_table td{
        padding:10px;
    }

</style>


<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">School Registeration</h1>
                </div>
                <div class="panel-body">
                    {% if is_registered %}
                    <script>alert("You are successfully registered with UserName:{{user_name}} , Password: {{ pass }} ")</script>
                    {% else %}
                    <form action="http://127.0.0.1:8000/school/" method="post">
                        {% csrf_token %}
                        <p class="bs-component">
                        <table class="school_form_table">
                            <tr>
                                <td>{{ form.name.label_tag }}</td>
                                <td>{{ form.name }}</td>
                            </tr>
                            <tr>
                                <td>{{ form.pass1.label_tag }}</td>
                                <td>{{ form.pass1}}</td>
                            </tr>

                            <tr>
                                <td>{{ form.state.label_tag }}</td>

                                <td>{{form.state}}<i style="position: absolute;left:440px"class="fa fa-chevron-down" aria-hidden="true"></i></td>



                            </tr>
                            <tr>
                                <td>{{ form.district.label_tag }}</td>
                                <td>{{ form.district}}<i style="position: absolute;left:490px"class="fa fa-chevron-down" aria-hidden="true"></i></td>
                            </tr>
                            <tr>
                                <td>{{ form.city.label_tag }}</td>
                                <td>{{ form.city}}<i style="position: absolute;left:690px"class="fa fa-chevron-down" aria-hidden="true"></i></td>
                            </tr>
                            <tr>
                                <td>{{ form.timing.label_tag }}</td>
                                <td>{{ form.timing}}</td>
                            </tr>
                            <tr>
                                <td>{{ form.address.label_tag }}</td>
                                <td>{{ form.address}}</td>
                            </tr>
                            <tr>
                                <td>{{ form.latitude.label_tag }}</td>
                                <td>{{ form.latitude}}</td>
                            </tr>
                            <tr>
                                <td>{{ form.longitude.label_tag }}</td>
                                <td>{{ form.longitude}}</td>
                            </tr>
                            <tr>
                                <td>{{ form.numOfStudents.label_tag }}</td>
                                <td>{{ form.numOfStudents}}</td>
                            </tr>
                            <tr>
                                <td>{{ form.numOfTeachers.label_tag }}</td>
                                <td>{{ form.numOfTeachers}}</td>
                            </tr>
                            <tr>
                                <td>{{ form.wifi_zone.label_tag }}</td>
                                <td>{{ form.wifi_zone}}</td>
                            </tr>

                        </table>

                        </p>
                        <p class="bs-component">
                        <center>
                            <input class="btn btn-success btn-sm" type="submit" value="Submit" onclick="return enableInput()" />
                        </center>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endif %}


{% endblock %}
{% block additional_scripts %}
<script >
    $('#id_state').select2();
    $('#id_district').select2();
    $('#id_city').select2();
</script>
{% endblock %}

templates/user_valid.html
{% extends 'base.html' %}

{% block content %}

<h1>
yoyo
</h1>

{% endblock %}